pipeline:
  name: deploy-a-bucket
  identifier: deployabucket
  projectIdentifier: sampleproject1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: deploy s3 bucket
        identifier: deploy_s3_bucket
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformPlan
                  name: TF Plan
                  identifier: TF_Plan
                  spec:
                    provisionerIdentifier: s3_bucket_deploy
                    configuration:
                      command: Apply
                      configFiles:
                        store:
                          spec:
                            connectorRef: account.TCShain_GitHub
                            repoName: harness-templates
                            gitFetchType: Branch
                            branch: main
                            folderPath: aws/terraform/tfstate
                          type: Github
                      varFiles:
                        - varFile:
                            spec:
                              content: |
                                aws_access_key = "AKIAYMVTY65Q675WRUWN"
                                aws_secret_key = "<+secrets.getValue("account.control_aws_secret_key")>"
                                region         = "<+stage.variables.aws_region>"
                            identifier: tf_provider_creds
                            type: Inline
                      secretManagerRef: harnessSecretManager
                  timeout: 10m
              - step:
                  type: HarnessApproval
                  name: Approval
                  identifier: Approval
                  spec:
                    approvalMessage: Please review the following information and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      userGroups:
                        - account.Admins
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
              - step:
                  type: TerraformApply
                  name: TerraformApply_1
                  identifier: TerraformApply_1
                  spec:
                    provisionerIdentifier: s3_bucket_deploy
                    configuration:
                      type: InheritFromPlan
                  timeout: 10m
        tags: {}
        variables:
          - name: aws_region
            type: String
            description: ""
            value: us-east-1
